version: '1.0'

stages:
- build
- push

steps:
  build_step:
    title: "Building production image"
    stage: build
    type: build
    dockerfile: Dockerfile
    image_name: codefresh/cf-webhook

  PushingToDockerRegistry:
    title: Pushing to Docker Registry
    type: push
    candidate: '${{build_step}}'
    tag: 'latest'
    registry: dockerhub
    when:
      branch:
        only:
          - master

